Criação do endpoint para exibir lista de livros
MILTONRUBRO/nossa-casa-do-codigo pull request #7
Opened 2020-03-28 03:38 UTC by MILTONRUBRO

2020-03-28 03:58 UTC, asouza requested changes

2020-03-28 03:58 UTC, asouza commented on src/main/java/br/com/devmos/apicdc/controllers/HomeController.java
> +	LivroRepository livroRepository;
Não faz diferença aqui, mas geralmente deixamos privado. Mas realmente não faz diferença aqui hehe

2020-03-28 03:58 UTC, asouza commented on src/main/java/br/com/devmos/apicdc/model/Livro.java
> +	public void setId(Long id) {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Não temos edição do id ou do título por enquanto, acho que não precisamos destes métodos aqui.

2020-03-28 03:58 UTC, asouza commented on src/main/java/br/com/devmos/apicdc/model/LivroToHome.java
> +	public void setId(Long id) {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Opa, mesma coisa dos setters aqui :).

2020-03-28 16:37 UTC, MILTONRUBRO commented on src/main/java/br/com/devmos/apicdc/model/Livro.java
> +	public void setId(Long id) {
fiz no automatico e acabei esquecendo rs

2020-03-29 01:17 UTC, asouza approved these changes

2020-03-29 01:18 UTC, merged